
pull_request_rules:
  - name: Dependabot
    conditions: []
    actions:
      queue:
queue_rules:
  - name: dependabot
    batch_size: 10
    batch_max_wait_time: 30 min
    queue_conditions:
      - author=dependabot[bot]
      - check-success=all-tests-succeeded
    merge_conditions: []
    merge_method: merge
