name: Checkout Rust Project
description: Performs an actions/checkout and installs the Rust toolchain

inputs:
  rust-profile:
    description: The rust toolchain profile
    required: false
    default: minimal
  rust-toolchain:
    description: The rust toolchain to install
    required: false
    default: stable
  rust-default:
    description: Use the default toolchain
    required: false
    default: "true"
  rust-components:
    description: A list of rust toolchain components to install
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: tomphp/github-actions/cache-cargo-dependencies@v0.1.0
    - uses: actions-rs/toolchain@v1.0.7
      with:
        profile: ${{ inputs.rust-profile }}
        toolchain: ${{ inputs.rust-toolchain }}
        default: ${{ inputs.rust-default }}
        components: ${{ inputs.rust-components }}
