on:
  push:
    branches: ["*"]
  pull_request:

permissions:
  contents: write

jobs:
  check-conventional-commits:
    uses: armakuni/github-actions/.github/workflows/check-conventional-commits.yml@v0.19.0

  test-checkout-rust-project:
    uses: ./.github/workflows/test-checkout-rust-project.yml

  test-determine-binary-name:
    uses: ./.github/workflows/test-determine-binary-name.yml

  test-determine-release-url:
    uses: ./.github/workflows/test-determine-release-url.yml

  test-install-release-binary:
    uses: ./.github/workflows/test-install-release-binary.yml

  all-tests-succeeded:
    needs:
      - check-conventional-commits
      - test-checkout-rust-project
      - test-determine-binary-name
      - test-determine-release-url
      - test-install-release-binary
    runs-on: ubuntu-latest
    steps:
      - run: echo OK

  release:
    if: github.ref == 'refs/heads/main'
    needs:
      - all-tests-succeeded
    uses: armakuni/github-actions/.github/workflows/tag-and-release.yml@v0.19.0
