on:
  push:
    branches: ["*"]
  pull_request:

permissions:
  contents: write

jobs:    
  test-checkout-rust-project:
    uses: ./.github/workflows/test-checkout-rust-project.yml

  all-tests-succeeded:
    needs:
      - test-checkout-rust-project
    runs-on: ubuntu-latest
    steps:
      - run: echo OK

  release:
    if: github.ref == 'refs/heads/main'
    needs:
      - all-tests-succeeded
    uses: armakuni/github-actions/.github/workflows/tag-and-release.yml@v0.18.1
