on:
  workflow_call:

jobs:
  test-with-no-version:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./install-release-binary
        id: run-action
        with:
          binary-name: specdown
          owner: specdown
          repository: specdown
      - run: specdown --version

  # TODO fix this (there is an error in the specdown pipeline)
  # test-with-version:
  #   strategy:
  #     matrix:
  #       os:
  #         - ubuntu-latest
  #         - windows-latest
  #         - macos-latest
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./install-release-binary
  #       id: run-action
  #       with:
  #         binary-name: specdown
  #         owner: specdown
  #         repository: specdown
  #         version: "1.2.85"
  #     - run: specdown --version | grep 1.2.85
