on:
  workflow_call:

jobs:
  test-with-default-arguments:
    strategy:
      matrix:
        os:
          - image: ubuntu-latest
            expected-url: https://github.com/example-org/example-app/releases/latest/download/my-binary-x86_64-unknown-linux-gnu
          - image: windows-latest
            expected-url: https://github.com/example-org/example-app/releases/latest/download/my-binary-x86_64-pc-windows-msvc.exe
          - image: macos-latest
            expected-url: https://github.com/example-org/example-app/releases/latest/download/my-binary-x86_64-apple-darwin
    runs-on: ${{ matrix.os.image }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./determine-release-url
        id: run-action
        with:
          name: my-binary
          owner: example-org
          respoitory: example-app
      - uses: armakuni/github-actions/assert-equals@v0.18.1
        name: Check url
        with:
          expected: ${{ matrix.os.expected-url }}
          actual: ${{ steps.run-action.outputs.url }}

  test-with-arguments:
    strategy:
      matrix:
        os:
          - image: ubuntu-latest
            expected-url: https://github.com/demo-org/demo-app/releases/latest/download/program-x86_64-unknown-linux-gnu
          - image: windows-latest
            expected-url: https://github.com/demo-org/demo-app/releases/latest/download/program-x86_64-pc-windows-msvc.exe
          - image: macos-latest
            expected-url: https://github.com/demo-org/demo-app/releases/latest/download/program-x86_64-apple-darwin
    runs-on: ${{ matrix.os.image }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./determine-release-url
        id: run-action
        with:
          name: program
          owner: demo-org
          respoitory: demo-app
          linux-suffix: linux
          windows-suffix: windows
          macos-suffix: macos
      - uses: armakuni/github-actions/assert-equals@v0.18.1
        name: Check url
        with:
          expected: ${{ matrix.os.expected-url }}
          actual: ${{ steps.run-action.outputs.url }}
