on:
  workflow_call:

jobs:
  test-with-no-version:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./install-release-binary
        id: run-action
        with:
          binary-name: versioned-files
          owner: tomphp
          repository: versioned-files
      - run: versioned-files --version

  test-with-version:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./install-release-binary
        id: run-action
        with:
          binary-name: versioned-files
          owner: tomphp
          repository: versioned-files
          version: "0.2.2"
      - run: versioned-files --version | grep 0.2.2
